1. Import the numpy package under the name np (★☆☆)


In [2]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

In [16]:
a = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
np.arange(10, 50)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5.Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6.Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

In [37]:
a = [1,2,0,0,4,0]

np.nonzero(a)

(array([0, 1, 4]),)

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

In [39]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

In [50]:
a = np.random.random((3,3,3))
a

array([[[0.38436449, 0.31807486, 0.30337546],
        [0.33036294, 0.81644304, 0.02788717],
        [0.69721893, 0.38191515, 0.16043615]],

       [[0.68900356, 0.2528979 , 0.48235202],
        [0.85058729, 0.86965441, 0.69345142],
        [0.43899021, 0.03531869, 0.97085353]],

       [[0.34165477, 0.23153391, 0.04472145],
        [0.44047427, 0.1117492 , 0.77415624],
        [0.03622328, 0.44458696, 0.79168352]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

In [82]:
i = np.random.random((10,10))
i


array([[0.56263852, 0.41485162, 0.48775044, 0.87570195, 0.00360279,
        0.37535422, 0.73333229, 0.52024468, 0.98039129, 0.91183371],
       [0.85429359, 0.37798458, 0.51863354, 0.91458535, 0.02504355,
        0.50376927, 0.49426742, 0.87198726, 0.22597787, 0.97669322],
       [0.50733961, 0.02424735, 0.69077053, 0.39549001, 0.96636217,
        0.41769093, 0.30339226, 0.91234   , 0.34120461, 0.65956104],
       [0.33317773, 0.83398285, 0.8145936 , 0.97333688, 0.33811878,
        0.98678821, 0.66662554, 0.01626526, 0.37767305, 0.13617724],
       [0.9060517 , 0.67881429, 0.40764802, 0.86101059, 0.36670703,
        0.49539774, 0.75897393, 0.06385382, 0.14864255, 0.77596159],
       [0.07154593, 0.6531979 , 0.89040016, 0.19150212, 0.91555643,
        0.41072221, 0.88985983, 0.68474527, 0.82688346, 0.96387213],
       [0.21500594, 0.38812671, 0.38942814, 0.99479996, 0.18133754,
        0.92212356, 0.05703084, 0.50898476, 0.19269019, 0.80133629],
       [0.19082686, 0.49029963, 0.8256782

In [83]:
np.min(i)

0.003602791334754829

In [84]:
np.max(i)

0.9947999623308788

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

In [92]:
a = np.random.random(30)
a

array([0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781,
       0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ,
       0.13623432, 0.54413629, 0.51817635, 0.76685511, 0.93385014,
       0.08970338, 0.19577126, 0.99419368, 0.2351805 , 0.23898637,
       0.62909983, 0.73495258, 0.68834438, 0.03113075, 0.90251384,
       0.28643533, 0.55561256, 0.37642024, 0.02662436, 0.49414912])

In [93]:
np.mean(a)

0.4919474657842404

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

In [104]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

In [106]:
a = np.random.random((5,5))
a

array([[0.83471509, 0.36698733, 0.51538211, 0.47237913, 0.38615209],
       [0.744137  , 0.33524208, 0.59543829, 0.31613338, 0.34625042],
       [0.24483181, 0.69795016, 0.21208083, 0.26729317, 0.37389408],
       [0.57308851, 0.91735808, 0.81897594, 0.16318089, 0.02415477],
       [0.78465363, 0.26485738, 0.33936706, 0.81436959, 0.80745472]])

In [108]:
b = (a-np.mean(a))/np.std(a)
b

array([[ 1.39994861, -0.49218299,  0.10812873, -0.06583424, -0.41465447],
       [ 1.03352678, -0.62060426,  0.43198553, -0.697906  , -0.57607144],
       [-0.98634721,  0.84668395, -1.11883701, -0.89548271, -0.46424264],
       [ 0.34157241,  1.73427002,  1.33627791, -1.31665533, -1.87906736],
       [ 1.19743149, -0.90533638, -0.60391721,  1.31764351,  1.28967031]])

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

In [111]:
a = np.arange(0,10)
b = np.arange(5,15)
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [112]:
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort



In [115]:
a = np.random.random(10)
a

array([0.93915573, 0.25683772, 0.0571346 , 0.38770822, 0.35709675,
       0.98638414, 0.93959064, 0.58277522, 0.99310313, 0.9899145 ])

In [116]:
np.sort(a)

array([0.0571346 , 0.25683772, 0.35709675, 0.38770822, 0.58277522,
       0.93915573, 0.93959064, 0.98638414, 0.9899145 , 0.99310313])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

In [168]:
a = np.random.random(10)
a


array([0.4574523 , 0.85048272, 0.23690505, 0.73024138, 0.50904647,
       0.41721275, 0.56122991, 0.52906708, 0.07618808, 0.69437145])

In [169]:
a_max = np.argmax(a)
a_max

1

In [170]:
a[5] = 0
a

array([0.4574523 , 0.85048272, 0.23690505, 0.73024138, 0.50904647,
       0.        , 0.56122991, 0.52906708, 0.07618808, 0.69437145])

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

In [152]:
a = np.random.random((3,3))
a

array([[0.63812829, 0.7894106 , 0.2291299 ],
       [0.72257143, 0.27579107, 0.05043075],
       [0.03106672, 0.69698148, 0.77232766]])

In [153]:
mean_a = np.mean(a, axis = 1, keepdims = True)
mean_a

array([[0.55222293],
       [0.34959775],
       [0.50012529]])

In [154]:
x = a - mean_a
x

array([[ 0.08590536,  0.23718767, -0.32309303],
       [ 0.37297368, -0.07380668, -0.299167  ],
       [-0.46905857,  0.19685619,  0.27220237]])

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [159]:
Z = np.arange(10000) 
Z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [162]:
np.random.shuffle(Z)
Z

array([8643, 2391, 2405, ..., 7596, 7607, 3638])